// Code generated by protoc-gen-go-pbex. DO NOT EDIT.
// version:
// 	protoc-gen-pbex v0.0.110
// 	protoc         v4.25.3
// source: api/im_match.proto

package api

// return empty means pass
func (m *DoReq) Validate() (errstr string) {
	if m.GetLan() != "zh" && m.GetLan() != "en" && m.GetLan() != "ru" && m.GetLan() != "de" && m.GetLan() != "fr" && m.GetLan() != "ar" && m.GetLan() != "ja" && m.GetLan() != "ko" && m.GetLan() != "hi" && m.GetLan() != "it" {
		return "field: lan in object: do_req check value str in failed"
	}
	if len(m.GetRegions()) <= 0 {
		return "field: regions in object: do_req check len gt failed"
	}
	if len(m.GetRegions()) > 3 {
		return "field: regions in object: do_req check len lte failed"
	}
	if len(m.GetActivities()) <= 0 {
		return "field: activities in object: do_req check len gt failed"
	}
	if len(m.GetActivities()) > 3 {
		return "field: activities in object: do_req check len lte failed"
	}
	return ""
}

// return empty means pass
func (m *ActivitiesReq) Validate() (errstr string) {
	if m.GetLan() != "zh" && m.GetLan() != "en" && m.GetLan() != "ru" && m.GetLan() != "de" && m.GetLan() != "fr" && m.GetLan() != "ar" && m.GetLan() != "ja" && m.GetLan() != "ko" && m.GetLan() != "hi" && m.GetLan() != "it" {
		return "field: lan in object: activities_req check value str in failed"
	}
	return ""
}

// return empty means pass
func (m *CitiesReq) Validate() (errstr string) {
	if m.GetLan() != "zh" && m.GetLan() != "en" && m.GetLan() != "ru" && m.GetLan() != "de" && m.GetLan() != "fr" && m.GetLan() != "ar" && m.GetLan() != "ja" && m.GetLan() != "ko" && m.GetLan() != "hi" && m.GetLan() != "it" {
		return "field: lan in object: cities_req check value str in failed"
	}
	return ""
}
