// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v4.25.3
// source: api/im_match.proto

//this is the app's name,all proto in this app must use this name as the proto package name

package api

import (
	_ "github.com/chenjie199234/Corelib/pbex"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StatusReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StatusReq) Reset() {
	*x = StatusReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_im_match_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatusReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusReq) ProtoMessage() {}

func (x *StatusReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_im_match_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusReq.ProtoReflect.Descriptor instead.
func (*StatusReq) Descriptor() ([]byte, []int) {
	return file_api_im_match_proto_rawDescGZIP(), []int{0}
}

type StatusResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Lan             string   `protobuf:"bytes,1,opt,name=lan,proto3" json:"lan,omitempty"`
	City            string   `protobuf:"bytes,2,opt,name=city,proto3" json:"city,omitempty"`
	Regions         []string `protobuf:"bytes,3,rep,name=regions,proto3" json:"regions,omitempty"`
	Activities      []string `protobuf:"bytes,4,rep,name=activities,proto3" json:"activities,omitempty"`
	Status          uint32   `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"` //0-depend on the fields up(empty:not in matching,not empty:in matching),>0-matched timestamp(unit seconds)
	MatchedRegion   string   `protobuf:"bytes,6,opt,name=matched_region,json=matchedRegion,proto3" json:"matched_region,omitempty"`
	MatchedActivity string   `protobuf:"bytes,7,opt,name=matched_activity,json=matchedActivity,proto3" json:"matched_activity,omitempty"`
}

func (x *StatusResp) Reset() {
	*x = StatusResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_im_match_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StatusResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResp) ProtoMessage() {}

func (x *StatusResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_im_match_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResp.ProtoReflect.Descriptor instead.
func (*StatusResp) Descriptor() ([]byte, []int) {
	return file_api_im_match_proto_rawDescGZIP(), []int{1}
}

func (x *StatusResp) GetLan() string {
	if x != nil {
		return x.Lan
	}
	return ""
}

func (x *StatusResp) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *StatusResp) GetRegions() []string {
	if x != nil {
		return x.Regions
	}
	return nil
}

func (x *StatusResp) GetActivities() []string {
	if x != nil {
		return x.Activities
	}
	return nil
}

func (x *StatusResp) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *StatusResp) GetMatchedRegion() string {
	if x != nil {
		return x.MatchedRegion
	}
	return ""
}

func (x *StatusResp) GetMatchedActivity() string {
	if x != nil {
		return x.MatchedActivity
	}
	return ""
}

type DoReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Lan        string   `protobuf:"bytes,1,opt,name=lan,proto3" json:"lan,omitempty"`
	City       string   `protobuf:"bytes,2,opt,name=city,proto3" json:"city,omitempty"`
	Regions    []string `protobuf:"bytes,3,rep,name=regions,proto3" json:"regions,omitempty"`
	Activities []string `protobuf:"bytes,4,rep,name=activities,proto3" json:"activities,omitempty"`
}

func (x *DoReq) Reset() {
	*x = DoReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_im_match_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoReq) ProtoMessage() {}

func (x *DoReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_im_match_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoReq.ProtoReflect.Descriptor instead.
func (*DoReq) Descriptor() ([]byte, []int) {
	return file_api_im_match_proto_rawDescGZIP(), []int{2}
}

func (x *DoReq) GetLan() string {
	if x != nil {
		return x.Lan
	}
	return ""
}

func (x *DoReq) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *DoReq) GetRegions() []string {
	if x != nil {
		return x.Regions
	}
	return nil
}

func (x *DoReq) GetActivities() []string {
	if x != nil {
		return x.Activities
	}
	return nil
}

type DoResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DoResp) Reset() {
	*x = DoResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_im_match_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoResp) ProtoMessage() {}

func (x *DoResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_im_match_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoResp.ProtoReflect.Descriptor instead.
func (*DoResp) Descriptor() ([]byte, []int) {
	return file_api_im_match_proto_rawDescGZIP(), []int{3}
}

type CancelReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CancelReq) Reset() {
	*x = CancelReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_im_match_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CancelReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelReq) ProtoMessage() {}

func (x *CancelReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_im_match_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelReq.ProtoReflect.Descriptor instead.
func (*CancelReq) Descriptor() ([]byte, []int) {
	return file_api_im_match_proto_rawDescGZIP(), []int{4}
}

type CancelResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CancelResp) Reset() {
	*x = CancelResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_im_match_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CancelResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelResp) ProtoMessage() {}

func (x *CancelResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_im_match_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelResp.ProtoReflect.Descriptor instead.
func (*CancelResp) Descriptor() ([]byte, []int) {
	return file_api_im_match_proto_rawDescGZIP(), []int{5}
}

type ActivityInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Min  uint32 `protobuf:"varint,2,opt,name=min,proto3" json:"min,omitempty"`
	Max  uint32 `protobuf:"varint,3,opt,name=max,proto3" json:"max,omitempty"`
}

func (x *ActivityInfo) Reset() {
	*x = ActivityInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_im_match_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActivityInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivityInfo) ProtoMessage() {}

func (x *ActivityInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_im_match_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivityInfo.ProtoReflect.Descriptor instead.
func (*ActivityInfo) Descriptor() ([]byte, []int) {
	return file_api_im_match_proto_rawDescGZIP(), []int{6}
}

func (x *ActivityInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ActivityInfo) GetMin() uint32 {
	if x != nil {
		return x.Min
	}
	return 0
}

func (x *ActivityInfo) GetMax() uint32 {
	if x != nil {
		return x.Max
	}
	return 0
}

type ActivitiesReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Lan string `protobuf:"bytes,1,opt,name=lan,proto3" json:"lan,omitempty"`
}

func (x *ActivitiesReq) Reset() {
	*x = ActivitiesReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_im_match_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActivitiesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivitiesReq) ProtoMessage() {}

func (x *ActivitiesReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_im_match_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivitiesReq.ProtoReflect.Descriptor instead.
func (*ActivitiesReq) Descriptor() ([]byte, []int) {
	return file_api_im_match_proto_rawDescGZIP(), []int{7}
}

func (x *ActivitiesReq) GetLan() string {
	if x != nil {
		return x.Lan
	}
	return ""
}

type ActivitiesResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Infos []*ActivityInfo `protobuf:"bytes,1,rep,name=infos,proto3" json:"infos,omitempty"`
}

func (x *ActivitiesResp) Reset() {
	*x = ActivitiesResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_im_match_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActivitiesResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivitiesResp) ProtoMessage() {}

func (x *ActivitiesResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_im_match_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivitiesResp.ProtoReflect.Descriptor instead.
func (*ActivitiesResp) Descriptor() ([]byte, []int) {
	return file_api_im_match_proto_rawDescGZIP(), []int{8}
}

func (x *ActivitiesResp) GetInfos() []*ActivityInfo {
	if x != nil {
		return x.Infos
	}
	return nil
}

type CityInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Regions []string `protobuf:"bytes,2,rep,name=regions,proto3" json:"regions,omitempty"`
}

func (x *CityInfo) Reset() {
	*x = CityInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_im_match_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CityInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CityInfo) ProtoMessage() {}

func (x *CityInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_im_match_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CityInfo.ProtoReflect.Descriptor instead.
func (*CityInfo) Descriptor() ([]byte, []int) {
	return file_api_im_match_proto_rawDescGZIP(), []int{9}
}

func (x *CityInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CityInfo) GetRegions() []string {
	if x != nil {
		return x.Regions
	}
	return nil
}

type CitiesReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Lan string `protobuf:"bytes,1,opt,name=lan,proto3" json:"lan,omitempty"`
}

func (x *CitiesReq) Reset() {
	*x = CitiesReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_im_match_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CitiesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CitiesReq) ProtoMessage() {}

func (x *CitiesReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_im_match_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CitiesReq.ProtoReflect.Descriptor instead.
func (*CitiesReq) Descriptor() ([]byte, []int) {
	return file_api_im_match_proto_rawDescGZIP(), []int{10}
}

func (x *CitiesReq) GetLan() string {
	if x != nil {
		return x.Lan
	}
	return ""
}

type CitiesResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Infos []*CityInfo `protobuf:"bytes,1,rep,name=infos,proto3" json:"infos,omitempty"`
}

func (x *CitiesResp) Reset() {
	*x = CitiesResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_im_match_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CitiesResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CitiesResp) ProtoMessage() {}

func (x *CitiesResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_im_match_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CitiesResp.ProtoReflect.Descriptor instead.
func (*CitiesResp) Descriptor() ([]byte, []int) {
	return file_api_im_match_proto_rawDescGZIP(), []int{11}
}

func (x *CitiesResp) GetInfos() []*CityInfo {
	if x != nil {
		return x.Infos
	}
	return nil
}

var File_api_im_match_proto protoreflect.FileDescriptor

var file_api_im_match_proto_rawDesc = []byte{
	0x0a, 0x12, 0x61, 0x70, 0x69, 0x2f, 0x69, 0x6d, 0x5f, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x69, 0x6d, 0x1a, 0x0f, 0x70, 0x62, 0x65, 0x78, 0x2f, 0x70,
	0x62, 0x65, 0x78, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x0c, 0x0a, 0x0a, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x5f, 0x72, 0x65, 0x71, 0x22, 0xd7, 0x01, 0x0a, 0x0b, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x6c, 0x61, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6c, 0x61, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x69, 0x74,
	0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x69, 0x74, 0x79, 0x12, 0x18, 0x0a,
	0x07, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07,
	0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x61, 0x63, 0x74, 0x69, 0x76,
	0x69, 0x74, 0x69, 0x65, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x61, 0x63, 0x74,
	0x69, 0x76, 0x69, 0x74, 0x69, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x25, 0x0a, 0x0e, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x65, 0x64, 0x5f, 0x72, 0x65, 0x67, 0x69, 0x6f,
	0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x65, 0x64,
	0x52, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x12, 0x29, 0x0a, 0x10, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x65,
	0x64, 0x5f, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x79, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0f, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x65, 0x64, 0x41, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74,
	0x79, 0x22, 0xba, 0x01, 0x0a, 0x06, 0x64, 0x6f, 0x5f, 0x72, 0x65, 0x71, 0x12, 0x4e, 0x0a, 0x03,
	0x6c, 0x61, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x3c, 0xd2, 0x90, 0x4e, 0x02, 0x7a,
	0x68, 0xd2, 0x90, 0x4e, 0x02, 0x65, 0x6e, 0xd2, 0x90, 0x4e, 0x02, 0x72, 0x75, 0xd2, 0x90, 0x4e,
	0x02, 0x64, 0x65, 0xd2, 0x90, 0x4e, 0x02, 0x66, 0x72, 0xd2, 0x90, 0x4e, 0x02, 0x61, 0x72, 0xd2,
	0x90, 0x4e, 0x02, 0x6a, 0x61, 0xd2, 0x90, 0x4e, 0x02, 0x6b, 0x6f, 0xd2, 0x90, 0x4e, 0x02, 0x68,
	0x69, 0xd2, 0x90, 0x4e, 0x02, 0x69, 0x74, 0x52, 0x03, 0x6c, 0x61, 0x6e, 0x12, 0x12, 0x0a, 0x04,
	0x63, 0x69, 0x74, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x69, 0x74, 0x79,
	0x12, 0x22, 0x0a, 0x07, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28,
	0x09, 0x42, 0x08, 0x98, 0x90, 0x4e, 0x00, 0xb0, 0x90, 0x4e, 0x03, 0x52, 0x07, 0x72, 0x65, 0x67,
	0x69, 0x6f, 0x6e, 0x73, 0x12, 0x28, 0x0a, 0x0a, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x69,
	0x65, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x42, 0x08, 0x98, 0x90, 0x4e, 0x00, 0xb0, 0x90,
	0x4e, 0x03, 0x52, 0x0a, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x69, 0x65, 0x73, 0x22, 0x09,
	0x0a, 0x07, 0x64, 0x6f, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x22, 0x0c, 0x0a, 0x0a, 0x63, 0x61, 0x6e,
	0x63, 0x65, 0x6c, 0x5f, 0x72, 0x65, 0x71, 0x22, 0x0d, 0x0a, 0x0b, 0x63, 0x61, 0x6e, 0x63, 0x65,
	0x6c, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x22, 0x47, 0x0a, 0x0d, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69,
	0x74, 0x79, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d,
	0x69, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x6d, 0x69, 0x6e, 0x12, 0x10, 0x0a,
	0x03, 0x6d, 0x61, 0x78, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x6d, 0x61, 0x78, 0x22,
	0x60, 0x0a, 0x0e, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x69, 0x65, 0x73, 0x5f, 0x72, 0x65,
	0x71, 0x12, 0x4e, 0x0a, 0x03, 0x6c, 0x61, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x42, 0x3c,
	0xd2, 0x90, 0x4e, 0x02, 0x7a, 0x68, 0xd2, 0x90, 0x4e, 0x02, 0x65, 0x6e, 0xd2, 0x90, 0x4e, 0x02,
	0x72, 0x75, 0xd2, 0x90, 0x4e, 0x02, 0x64, 0x65, 0xd2, 0x90, 0x4e, 0x02, 0x66, 0x72, 0xd2, 0x90,
	0x4e, 0x02, 0x61, 0x72, 0xd2, 0x90, 0x4e, 0x02, 0x6a, 0x61, 0xd2, 0x90, 0x4e, 0x02, 0x6b, 0x6f,
	0xd2, 0x90, 0x4e, 0x02, 0x68, 0x69, 0xd2, 0x90, 0x4e, 0x02, 0x69, 0x74, 0x52, 0x03, 0x6c, 0x61,
	0x6e, 0x22, 0x3a, 0x0a, 0x0f, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x69, 0x65, 0x73, 0x5f,
	0x72, 0x65, 0x73, 0x70, 0x12, 0x27, 0x0a, 0x05, 0x69, 0x6e, 0x66, 0x6f, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x69, 0x6d, 0x2e, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74,
	0x79, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x52, 0x05, 0x69, 0x6e, 0x66, 0x6f, 0x73, 0x22, 0x39, 0x0a,
	0x09, 0x63, 0x69, 0x74, 0x79, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x07, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x5c, 0x0a, 0x0a, 0x63, 0x69, 0x74, 0x69,
	0x65, 0x73, 0x5f, 0x72, 0x65, 0x71, 0x12, 0x4e, 0x0a, 0x03, 0x6c, 0x61, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x42, 0x3c, 0xd2, 0x90, 0x4e, 0x02, 0x7a, 0x68, 0xd2, 0x90, 0x4e, 0x02, 0x65,
	0x6e, 0xd2, 0x90, 0x4e, 0x02, 0x72, 0x75, 0xd2, 0x90, 0x4e, 0x02, 0x64, 0x65, 0xd2, 0x90, 0x4e,
	0x02, 0x66, 0x72, 0xd2, 0x90, 0x4e, 0x02, 0x61, 0x72, 0xd2, 0x90, 0x4e, 0x02, 0x6a, 0x61, 0xd2,
	0x90, 0x4e, 0x02, 0x6b, 0x6f, 0xd2, 0x90, 0x4e, 0x02, 0x68, 0x69, 0xd2, 0x90, 0x4e, 0x02, 0x69,
	0x74, 0x52, 0x03, 0x6c, 0x61, 0x6e, 0x22, 0x32, 0x0a, 0x0b, 0x63, 0x69, 0x74, 0x69, 0x65, 0x73,
	0x5f, 0x72, 0x65, 0x73, 0x70, 0x12, 0x23, 0x0a, 0x05, 0x69, 0x6e, 0x66, 0x6f, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x69, 0x6d, 0x2e, 0x63, 0x69, 0x74, 0x79, 0x5f, 0x69,
	0x6e, 0x66, 0x6f, 0x52, 0x05, 0x69, 0x6e, 0x66, 0x6f, 0x73, 0x32, 0xbd, 0x02, 0x0a, 0x05, 0x6d,
	0x61, 0x74, 0x63, 0x68, 0x12, 0x3c, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0e,
	0x2e, 0x69, 0x6d, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x5f, 0x72, 0x65, 0x71, 0x1a, 0x0f,
	0x2e, 0x69, 0x6d, 0x2e, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x22,
	0x11, 0x8a, 0x9f, 0x49, 0x04, 0x70, 0x6f, 0x73, 0x74, 0x92, 0x9f, 0x49, 0x05, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x12, 0x30, 0x0a, 0x02, 0x64, 0x6f, 0x12, 0x0a, 0x2e, 0x69, 0x6d, 0x2e, 0x64, 0x6f,
	0x5f, 0x72, 0x65, 0x71, 0x1a, 0x0b, 0x2e, 0x69, 0x6d, 0x2e, 0x64, 0x6f, 0x5f, 0x72, 0x65, 0x73,
	0x70, 0x22, 0x11, 0x8a, 0x9f, 0x49, 0x04, 0x70, 0x6f, 0x73, 0x74, 0x92, 0x9f, 0x49, 0x05, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x3c, 0x0a, 0x06, 0x63, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x12, 0x0e,
	0x2e, 0x69, 0x6d, 0x2e, 0x63, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x5f, 0x72, 0x65, 0x71, 0x1a, 0x0f,
	0x2e, 0x69, 0x6d, 0x2e, 0x63, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x22,
	0x11, 0x8a, 0x9f, 0x49, 0x04, 0x70, 0x6f, 0x73, 0x74, 0x92, 0x9f, 0x49, 0x05, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x12, 0x48, 0x0a, 0x0a, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x69, 0x65, 0x73,
	0x12, 0x12, 0x2e, 0x69, 0x6d, 0x2e, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69, 0x74, 0x69, 0x65, 0x73,
	0x5f, 0x72, 0x65, 0x71, 0x1a, 0x13, 0x2e, 0x69, 0x6d, 0x2e, 0x61, 0x63, 0x74, 0x69, 0x76, 0x69,
	0x74, 0x69, 0x65, 0x73, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x22, 0x11, 0x8a, 0x9f, 0x49, 0x04, 0x70,
	0x6f, 0x73, 0x74, 0x92, 0x9f, 0x49, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x3c, 0x0a, 0x06,
	0x63, 0x69, 0x74, 0x69, 0x65, 0x73, 0x12, 0x0e, 0x2e, 0x69, 0x6d, 0x2e, 0x63, 0x69, 0x74, 0x69,
	0x65, 0x73, 0x5f, 0x72, 0x65, 0x71, 0x1a, 0x0f, 0x2e, 0x69, 0x6d, 0x2e, 0x63, 0x69, 0x74, 0x69,
	0x65, 0x73, 0x5f, 0x72, 0x65, 0x73, 0x70, 0x22, 0x11, 0x8a, 0x9f, 0x49, 0x04, 0x70, 0x6f, 0x73,
	0x74, 0x92, 0x9f, 0x49, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x42, 0x25, 0x5a, 0x23, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x68, 0x65, 0x6e, 0x6a, 0x69, 0x65,
	0x31, 0x39, 0x39, 0x32, 0x33, 0x34, 0x2f, 0x69, 0x6d, 0x2f, 0x61, 0x70, 0x69, 0x3b, 0x61, 0x70,
	0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_im_match_proto_rawDescOnce sync.Once
	file_api_im_match_proto_rawDescData = file_api_im_match_proto_rawDesc
)

func file_api_im_match_proto_rawDescGZIP() []byte {
	file_api_im_match_proto_rawDescOnce.Do(func() {
		file_api_im_match_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_im_match_proto_rawDescData)
	})
	return file_api_im_match_proto_rawDescData
}

var file_api_im_match_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_api_im_match_proto_goTypes = []interface{}{
	(*StatusReq)(nil),      // 0: im.status_req
	(*StatusResp)(nil),     // 1: im.status_resp
	(*DoReq)(nil),          // 2: im.do_req
	(*DoResp)(nil),         // 3: im.do_resp
	(*CancelReq)(nil),      // 4: im.cancel_req
	(*CancelResp)(nil),     // 5: im.cancel_resp
	(*ActivityInfo)(nil),   // 6: im.activity_info
	(*ActivitiesReq)(nil),  // 7: im.activities_req
	(*ActivitiesResp)(nil), // 8: im.activities_resp
	(*CityInfo)(nil),       // 9: im.city_info
	(*CitiesReq)(nil),      // 10: im.cities_req
	(*CitiesResp)(nil),     // 11: im.cities_resp
}
var file_api_im_match_proto_depIdxs = []int32{
	6,  // 0: im.activities_resp.infos:type_name -> im.activity_info
	9,  // 1: im.cities_resp.infos:type_name -> im.city_info
	0,  // 2: im.match.status:input_type -> im.status_req
	2,  // 3: im.match.do:input_type -> im.do_req
	4,  // 4: im.match.cancel:input_type -> im.cancel_req
	7,  // 5: im.match.activities:input_type -> im.activities_req
	10, // 6: im.match.cities:input_type -> im.cities_req
	1,  // 7: im.match.status:output_type -> im.status_resp
	3,  // 8: im.match.do:output_type -> im.do_resp
	5,  // 9: im.match.cancel:output_type -> im.cancel_resp
	8,  // 10: im.match.activities:output_type -> im.activities_resp
	11, // 11: im.match.cities:output_type -> im.cities_resp
	7,  // [7:12] is the sub-list for method output_type
	2,  // [2:7] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_api_im_match_proto_init() }
func file_api_im_match_proto_init() {
	if File_api_im_match_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_im_match_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatusReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_im_match_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StatusResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_im_match_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DoReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_im_match_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DoResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_im_match_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CancelReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_im_match_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CancelResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_im_match_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ActivityInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_im_match_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ActivitiesReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_im_match_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ActivitiesResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_im_match_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CityInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_im_match_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CitiesReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_im_match_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CitiesResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_im_match_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_im_match_proto_goTypes,
		DependencyIndexes: file_api_im_match_proto_depIdxs,
		MessageInfos:      file_api_im_match_proto_msgTypes,
	}.Build()
	File_api_im_match_proto = out.File
	file_api_im_match_proto_rawDesc = nil
	file_api_im_match_proto_goTypes = nil
	file_api_im_match_proto_depIdxs = nil
}
